### ISSUE TITLE
Background image not displaying

### ISSUE THREAD

**Issue by joeshevland** [EFForg/actioncenter-feedback#10]
The background congress image on this one appears to 404 (or appears very briefly before disappearing)... suspect it might be my plugins acting up, as the CSS looks OK to me in the source:

```
https://act.eff.org/action/shut-the-nsa-s-backdoor-to-the-internet
```

In the web console it looks to be trying the following GET:

https://act.eff.org/action/%22https://act.eff.org/system/action_pages/background_images/000/000/059/original/downloads-bg.jpg?1403292713%22

Firefox 30, Linux Mint, Ghostery (whitelisted), ABE, Flashblock (disabled).

**Comment by thomasdavis** [comment]
Interesting one, I will investigate.

On Tue, Jun 24, 2014 at 7:10 PM, joeshevland notifications@github.com
wrote:

> The background congress image on this one appears to 404 (or appears very
> briefly before disappearing)... suspect it might be my plugins acting up,
> as the CSS looks OK to me in the source:
> 
> https://act.eff.org/action/shut-the-nsa-s-backdoor-to-the-internet
> 
> In the web console it looks to be trying the following GET:
> 
> https://act.eff.org/action/%22https://act.eff.org/system/action_pages/background_images/000/000/059/original/downloads-bg.jpg?1403292713%22
> 
> Firefox 30, Linux Mint, Ghostery (whitelisted), ABE, Flashblock (disabled).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EFForg/actioncenter-feedback/issues/10.

## 

Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by sinak** [comment]
Yep, I have an issue created in our own repo for this on FF. Seems to work fine on Chrome, but there's some weird inline CSS being added on FF.

**Comment by joeshevland** [comment]
Yeah I can't recall ever having this issue. I think if you use an absolute URL it behaves itself:

background: #cc0000 url("https://act.eff.org/system...

**Comment by liliakai** [comment]
Fixed.
