### ISSUE TITLE
Backend validation on registration form

### ISSUE THREAD

**Issue by joeshevland** [EFForg/actioncenter-feedback#11]
I'm not sure if this is a valid one, but if I edit the POST and change the email parameter on the signup form on:

  https://act.eff.org/register

to:

  test'; select%321

or similar, I get a 500 Internal Server error back from Phusion Passenger. This dodges the type="email" browser validation.

**Comment by thomasdavis** [comment]
Good catch, it shouldn't throw server errors. It should redirect as if it
was just an invalid input. Will work on it.

On Tue, Jun 24, 2014 at 7:22 PM, joeshevland notifications@github.com
wrote:

> I'm not sure if this is a valid one, but if I edit the POST and change the
> email parameter on the signup form on:
> 
> https://act.eff.org/register
> 
> to:
> 
> test'; select%321
> 
> or similar, I get a 500 Internal Server error back from Phusion Passenger.
> This dodges the type="email" browser validation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EFForg/actioncenter-feedback/issues/11.

## 

Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by Hainish** [comment]
I don't think this is an issue, since we get the same when we send just `test` as the email, and we're never sending any raw sql strings to any queries

**Comment by joeshevland** [comment]
Sounds fair, wasn't sure what was happening to it on the backend.
