### ISSUE TITLE
Informational message shown as error on forgot password page

### ISSUE THREAD

**Issue by scrozier** [EFForg/actioncenter-feedback#2]
When requesting a password reset, you enter your email. The next screen informs you that the password reset info has been sent, but it is shown as an error message. It should probably not be marked as an error, but rather as information.
![eff_action_center](https://cloud.githubusercontent.com/assets/203622/3345833/cde23fa6-f8bd-11e3-8569-5f2433379f5e.png)

**Comment by sinak** [comment]
Okay, just fixed this. Thanks!
