### ISSUE TITLE
Form autofills on iOS Safari?

### ISSUE THREAD

**Issue by scrozier** [EFForg/actioncenter-feedback#6]
When doing an "Email your representatives" function (for "End the NSA's Mass Spying"), when I get to the second form (first name, last name, phone, email, then the list of my representatives), the prefix and topic select widgets are pre-populated, apparentlly with the first item in the options list.

I think they should not be pre-populated.

This happens on iOS Safari, and doesn't happen on OS X Chrome.

**Comment by thomasdavis** [comment]
Working on it

**Comment by thomasdavis** [comment]
Should be fixed now.

Thanks again!
