### ISSUE TITLE
Progress indicator when signing up

### ISSUE THREAD

**Issue by joeshevland** [EFForg/actioncenter-feedback#8]
It wasn't obvious that anything was happening after I clicked the "Get Email Alerts", a progress indicator/spinner of some kind would be good. Took maybe 5 seconds to process and update the message on my connection (Firefox 30/Linux Mint, ABE, Ghostery).

**Comment by sinak** [comment]
Thanks @joeshevland. We have this as an issue and it'll be fixed before launch.

**Comment by liliakai** [comment]
Fixed

**Comment by joeshevland** [comment]
Looks good (as does the site in general), nice work.
